export interface MenuItem {
  id: string;
  name: string;
  descr: string;
  img: string;
  price: number;
}

export interface Subcategory {
  id: string;
  title: string;
  items: MenuItem[];
}

export interface Category {
  id: string;
  title: string;
  subcategories: Subcategory[];
}

export const menuList: Category[] = [
  {
    id: 'salads',
    title: 'Салати',
    subcategories: [
      {
        id: 'vegetable',
        title: 'Овочеві (на олії)',
        items: [
          {
            id: '010101',
            name: 'Салат з капусти',
            descr: 'капуста, морква, цибуля, олія',
            img: 'url.url',
            price: 60,
          },
          {
            id: '010102',
            name: 'Салат з огірків та помідорів',
            descr: 'огірок, помідор, цибуля, олія',
            img: 'url.url',
            price: 80,
          },
          {
            id: '010103',
            name: 'Салат "Джан"',
            descr: 'помідор, серце, яйце, перепілки, оливки, цибуля, олія',
            img: 'url.url',
            price: 150,
          },
          {
            id: '010104',
            name: 'Вітамінний',
            descr: 'буряк, морква, сир, бринза, оливки, олія',
            img: 'url.url',
            price: 70,
          },
          {
            id: '010105',
            name: 'Салат "Грецький"',
            descr: 'перець, огірок, помідор, оливки, цибуля, бринза',
            img: 'url.url',
            price: 100,
          },
          {
            id: '010106',
            name: 'Салат "Капрезо"',
            descr: 'сир моцарела, помідор, базилік, прованські трави',
            img: 'url.url',
            price: 200,
          },
        ],
      },
      {
        id: 'meat',
        title: 'Мясні (на майонезі)',
        items: [
          {
            id: '010201',
            name: 'Салат з курки',
            descr: 'курка, огірок, цибуля, яйце, майонез',
            img: 'url.url',
            price: 100,
          },
          {
            id: '010202',
            name: 'Салат "Царський"',
            descr: 'балик, помідор, огірок, морква, буряк, капуста',
            img: 'url.url',
            price: 80,
          },
          {
            id: '010203',
            name: 'Салат "Перчинка"',
            descr: "перець, м'ясо, яйце, цибуля, майонез",
            img: 'url.url',
            price: 90,
          },
          {
            id: '010204',
            name: 'Салат "Батумі"',
            descr: 'солений огірок, яйце, часник, телятина, майонез, горіхи',
            img: 'url.url',
            price: 95,
          },
          {
            id: '010205',
            name: 'Салат "Тбілісі"',
            descr: 'перець, курка, сулугуні, огірок, цибуля, майонез',
            img: 'url.url',
            price: 100,
          },
          {
            id: '010206',
            name: 'Салат з крабових паличок',
            descr: '',
            img: 'url.url',
            price: 85,
          },
        ],
      },
      {
        id: 'salad-leaves',
        title: 'З листя салату (на власних соусах',
        items: [
          {
            id: '010301',
            name: 'Салат з креветками',
            descr:
              'айзберг, рукола, авокадо, креветка, філадельфія, пармезан, чері, соус, яйце перепілки',
            img: 'url.url',
            price: 250,
          },
          {
            id: '010302',
            name: 'Цезар з куркою',
            descr:
              'айзберг, рукола, бекон, курка, чері, яйце перепілки, пармезан, крутони, соус',
            img: 'url.url',
            price: 250,
          },
          {
            id: '010303',
            name: 'Цезар з червоною рибою',
            descr:
              'айзберг, рукола, лосось, песто, пармезан, чері, крутони, соус',
            img: 'url.url',
            price: 250,
          },
          {
            id: '010304',
            name: 'Салат з теплою телятиною',
            descr: '',
            img: 'url.url',
            price: 240,
          },
          {
            id: '010305',
            name: 'Салат з печінкою та апельсином',
            descr: '',
            img: 'url.url',
            price: 220,
          },
        ],
      },
    ],
  },
  {
    id: 'flour-dishes',
    title: 'Страви з борошна',
    subcategories: [
      {
        id: 'khachapuri',
        title: 'Хачапурі',
        items: [
          {
            id: '020101',
            name: 'Хачапурі з бринзою',
            descr: '1 пор',
            img: 'url.url',
            price: 100,
          },
          {
            id: '020102',
            name: 'Хачапурі з сиром моцарела',
            descr: '1 пор',
            img: 'url.url',
            price: 100,
          },
          {
            id: '020103',
            name: 'Хачапурі з сиром сулугуні',
            descr: '1 пор',
            img: 'url.url',
            price: 100,
          },
          {
            id: '020104',
            name: "Хачапурі з бринзою та м'ясом",
            descr: '1 пор',
            img: 'url.url',
            price: 120,
          },
          {
            id: '020105',
            name: "Хачапурі з сулугуні та м'ясом",
            descr: '1 пор',
            img: 'url.url',
            price: 120,
          },
          {
            id: '020106',
            name: 'Хачапурі зелень та сулугуні',
            descr: '1 пор',
            img: 'url.url',
            price: 100,
          },
          {
            id: '020107',
            name: 'Хачапурі по-мегрельські',
            descr: '1 пор',
            img: 'url.url',
            price: 170,
          },
          {
            id: '020108',
            name: 'Хачапурі по-аджарські',
            descr: '1 пор',
            img: 'url.url',
            price: 170,
          },
          {
            id: '020109',
            name: 'Хачапурі по-аджарські з лососем',
            descr: '1 пор',
            img: 'url.url',
            price: 220,
          },
        ],
      },
      {
        id: 'khinkali-etc',
        title: 'Хінкалі * Пельмені * Вареники',
        items: [
          {
            id: '020201',
            name: 'Хінкалі',
            descr: '1 пор',
            img: 'url.url',
            price: 120,
          },
          {
            id: '020202',
            name: 'Пельмені',
            descr: '1 пор',
            img: 'url.url',
            price: 90,
          },
          {
            id: '020203',
            name: 'Вареники з картоплею та сиром',
            descr: '1 пор',
            img: 'url.url',
            price: 90,
          },
          {
            id: '020204',
            name: 'Вареники з лівером',
            descr: '1 пор',
            img: 'url.url',
            price: 95,
          },
          {
            id: '020205',
            name: "Вареники з м'ясом",
            descr: '1 пор',
            img: 'url.url',
            price: 95,
          },
        ],
      },
      {
        id: 'pies-pizzas',
        title: 'Пироги * Піца',
        items: [
          {
            id: '020301',
            name: 'Піца "Джан"',
            descr:
              'балик, мясо, філе свинини, кукурудза, перець,гриби, сир, помідори, майонез, соус',
            img: 'url.url',
            price: 300,
          },
          {
            id: '020302',
            name: 'Осетинський пиріг з мясом',
            descr: '1 пор',
            img: 'url.url',
            price: 230,
          },
          {
            id: '020303',
            name: 'Осетинський пиріг з моцарелою',
            descr: '1 пор',
            img: 'url.url',
            price: 200,
          },
          {
            id: '020304',
            name: 'Лаваш тонкий листовий',
            descr: '1шт',
            img: 'url.url',
            price: 20,
          },
          {
            id: '020305',
            name: 'Хліб',
            descr: '100г',
            img: 'url.url',
            price: 15,
          },
        ],
      },
    ],
  },
  {
    id: 'meat',
    title: 'Страви з мяса',
    subcategories: [
      {
        id: 'mangal',
        title: 'На мангалі',
        items: [
          {
            id: '030101',
            name: 'Шашлик зі свинини',
            descr: 'вага в сирому вигляді - 100/65/35',
            img: 'url.url',
            price: 60,
          },
          {
            id: '030102',
            name: 'Люля кебаб',
            descr: 'свинина, курятина, сало, кінза, цибуля (200/140/30)',
            img: 'url.url',
            price: 170,
          },
          {
            id: '030103',
            name: 'Люля кебаб з курки та телятини',
            descr: '200/145/25',
            img: 'url.url',
            price: 170,
          },
          {
            id: '030104',
            name: 'Шашлик курячий',
            descr: '100/70/30',
            img: 'url.url',
            price: 50,
          },
        ],
      },
      {
        id: 'hot-meat-dishes',
        title: 'Гарячі страви з мяса',
        items: [
          {
            id: '030201',
            name: 'Сет "Курча"',
            descr:
              'філе курки, шашлик курячий, ципля табака, овочі на грилі, картопля фрі, соус',
            img: 'url.url',
            price: 1900,
          },
          {
            id: '030202',
            name: "М'ясо по домашньому",
            descr:
              'свинина, цибуля, сіль, перець, вага в сирому вигляді (100г)',
            img: 'url.url',
            price: 58,
          },
          {
            id: '030203',
            name: 'Стейк на ребрі',
            descr: 'свинина, вага в сирому вигляді (100/70/30)',
            img: 'url.url',
            price: 55,
          },
          {
            id: '030204',
            name: "М'ясне плато",
            descr:
              'шашлик, стейк, крильця, картопля, овочі печені, купати, абхазурі, лаваш, соуси',
            img: 'url.url',
            price: 2200,
          },
          {
            id: '030205',
            name: 'Сет "Генацвале"',
            descr: '1 пор',
            img: 'url.url',
            price: 650,
          },
          {
            id: '030206',
            name: 'Рулька запечена з капустою',
            descr: 'рулька свинна, капуста, картопля, соус гірчичний',
            img: 'url.url',
            price: 400,
          },
          {
            id: '030207',
            name: 'Купати',
            descr: 'свинні ковбаски з кінзою',
            img: 'url.url',
            price: 170,
          },
          {
            id: '030208',
            name: 'Абхазурі',
            descr: 'свинина, телятина, барбарис, лаваш, спеції',
            img: 'url.url',
            price: 170,
          },
          {
            id: '030209',
            name: 'Ені з горіхами',
            descr: 'язик, горіхи, сметана, цибуля, часник',
            img: 'url.url',
            price: 100,
          },
          {
            id: '030210',
            name: 'Твіні з грибами',
            descr: 'мозги телячі, гриби, сметана, цибуля',
            img: 'url.url',
            price: 100,
          },
        ],
      },
      {
        id: 'hot-meat-dishes-2',
        title: 'Гарячі страви з мяса',
        items: [
          {
            id: '030301',
            name: 'Кучмачі',
            descr: 'сердечка курячі та шлуночки',
            img: 'url.url',
            price: 150,
          },
          {
            id: '030302',
            name: 'Ципля "Табака"',
            descr: '100г',
            img: 'url.url',
            price: 29,
          },
          {
            id: '030303',
            name: 'Реберця в медовій глазурі',
            descr: 'ребра свинні, сіль, перець, мед, лимонний сік (100г)',
            img: 'url.url',
            price: 48,
          },
          {
            id: '030304',
            name: 'Перепілка з соусом',
            descr: '100г',
            img: 'url.url',
            price: 51,
          },
          {
            id: '030305',
            name: 'Тарілка грузина',
            descr: "салат огірки та помідори, м'ясо, картопля",
            img: 'url.url',
            price: 300,
          },
          {
            id: '030306',
            name: 'Чахохбілі',
            descr: 'курка, цибуля, помідори, вино, спеції',
            img: 'url.url',
            price: 370,
          },
          {
            id: '030307',
            name: 'Печінка з грибами',
            descr: 'печінка теляча, гриби, цибуля (100г)',
            img: 'url.url',
            price: 40,
          },
          {
            id: '030308',
            name: 'Крильця курячі',
            descr: '1 пор',
            img: 'url.url',
            price: 170,
          },
          {
            id: '030309',
            name: 'Жульєн курячий',
            descr: '1 пор',
            img: 'url.url',
            price: 38,
          },
        ],
      },
    ],
  },
  {
    id: 'made-to-order-dishes',
    title: 'Страви на замовлення',
    subcategories: [
      {
        id: 'meat-dishes',
        title: 'Мясні страви',
        items: [
          {
            id: '040101',
            name: 'Ребра з чорносливом',
            descr: '100г',
            img: 'url.url',
            price: 50,
          },
          {
            id: '040102',
            name: 'Відбивна свинна',
            descr: '1шт',
            img: 'url.url',
            price: 80,
          },
          {
            id: '040103',
            name: 'Відбивна куряча',
            descr: '1шт',
            img: 'url.url',
            price: 80,
          },
          {
            id: '040104',
            name: 'Котлета свинна',
            descr: '300г',
            img: 'url.url',
            price: 150,
          },
          {
            id: '040105',
            name: 'Курячі рулетики з сиром',
            descr: '1 пор',
            img: 'url.url',
            price: 180,
          },
          {
            id: '040106',
            name: 'Крученики з грибами',
            descr: '1 пор',
            img: 'url.url',
            price: 180,
          },
          {
            id: '040107',
            name: 'Стейк філе курки',
            descr: '100г',
            img: 'url.url',
            price: 30,
          },
        ],
      },
      {
        id: 'not-meat-dishes',
        title: ' НеМясні страви',
        items: [
          {
            id: '040201',
            name: 'Перець фарширований',
            descr: '1 пор',
            img: 'url.url',
            price: 280,
          },
          {
            id: '040202',
            name: 'Голубці',
            descr: '1 пор',
            img: 'url.url',
            price: 100,
          },
          {
            id: '040203',
            name: 'Зрази',
            descr: '1 пор',
            img: 'url.url',
            price: 90,
          },
          {
            id: '040204',
            name: "Млинці з м'ясом",
            descr: '1 пор',
            img: 'url.url',
            price: 75,
          },
          {
            id: '040205',
            name: 'Млинці з грибами',
            descr: '1 пор',
            img: 'url.url',
            price: 75,
          },
          {
            id: '040206',
            name: 'Млинці з куркою',
            descr: '1 пор',
            img: 'url.url',
            price: 85,
          },
          {
            id: '040207',
            name: 'Млинці з сиром',
            descr: '1 пор',
            img: 'url.url',
            price: 75,
          },
          {
            id: '040208',
            name: 'Млинці з маком',
            descr: '1 пор',
            img: 'url.url',
            price: 70,
          },
          {
            id: '040209',
            name: "Салат Олів'є",
            descr: '1 пор',
            img: 'url.url',
            price: 80,
          },
        ],
      },
    ],
  },
  {
    id: 'drinks',
    title: 'Напої',
    subcategories: [
      {
        id: 'tea-coffee',
        title: 'Кава * Чай',
        items: [
          {
            id: '050101',
            name: 'Еспрессо',
            descr: '1 пор',
            img: 'url.url',
            price: 30,
          },
          {
            id: '050102',
            name: 'Еспрессо з молоком',
            descr: '1 пор',
            img: 'url.url',
            price: 35,
          },
          {
            id: '050103',
            name: 'Американо',
            descr: '1 пор',
            img: 'url.url',
            price: 35,
          },
          {
            id: '050104',
            name: 'Американо з молоком',
            descr: '1 пор',
            img: 'url.url',
            price: 55,
          },
          {
            id: '050105',
            name: 'Лате',
            descr: '1 пор',
            img: 'url.url',
            price: 55,
          },
          {
            id: '050106',
            name: 'Чай в пакетику',
            descr: '1 пор',
            img: 'url.url',
            price: 30,
          },
          {
            id: '050107',
            name: 'Чай в заварнику (асортимент)',
            descr: '1 пор',
            img: 'url.url',
            price: 80,
          },
        ],
      },
      {
        id: 'non-alcohol',
        title: 'Безалкогольні напої',
        items: [
          {
            id: '050201',
            name: 'Сік в асортименті',
            descr: '1л',
            img: 'url.url',
            price: 110,
          },
          {
            id: '050202',
            name: 'Сік',
            descr: '0,5л',
            img: 'url.url',
            price: 70,
          },
          {
            id: '050203',
            name: 'Сік',
            descr: '0,2л',
            img: 'url.url',
            price: 30,
          },
          {
            id: '050204',
            name: 'Мохіто',
            descr: '1 пор',
            img: 'url.url',
            price: 75,
          },
          {
            id: '050205',
            name: 'Лимонад в асортименті',
            descr: '1 пор',
            img: 'url.url',
            price: 75,
          },
          {
            id: '050206',
            name: 'Сітро грузинський букет',
            descr: '1л',
            img: 'url.url',
            price: 85,
          },
          {
            id: '050207',
            name: 'Сітро грузинський букет',
            descr: '0,5л',
            img: 'url.url',
            price: 80,
          },
          {
            id: '050208',
            name: 'Вода Моршинська',
            descr: '1,5л',
            img: 'url.url',
            price: 45,
          },
          {
            id: '050209',
            name: 'Вода Моршинська',
            descr: '0,75л',
            img: 'url.url',
            price: 35,
          },
          {
            id: '050210',
            name: 'Вода Моршинська',
            descr: '0,75л',
            img: 'url.url',
            price: 30,
          },
          {
            id: '050211',
            name: 'Поляна квасова',
            descr: '1,5л',
            img: 'url.url',
            price: 60,
          },
          {
            id: '050212',
            name: 'Поляна квасова',
            descr: '0,5л',
            img: 'url.url',
            price: 65,
          },
          {
            id: '050213',
            name: 'Боржомі',
            descr: '0,5л',
            img: 'url.url',
            price: 90,
          },
        ],
      },
    ],
  },
  {
    id: 'hot-dishes',
    title: 'Гарячі страви',
    subcategories: [
      {
        id: 'hot-dishes-sub',
        title: 'Гарячі страви',
        items: [
          {
            id: '060101',
            name: 'Аджабсандалі',
            descr: 'овочі з горіхом, перець, баклажан, помідор, цибуля',
            img: 'url.url',
            price: 80,
          },
          {
            id: '060102',
            name: 'Долма',
            descr: 'голубці по вірменські у виноградному листі',
            img: 'url.url',
            price: 190,
          },
          {
            id: '060103',
            name: 'Шампіньйони з сулугуні в кецах',
            descr: 'гриби, сир сулугуні, часник, вершкове масло',
            img: 'url.url',
            price: 120,
          },
          {
            id: '060104',
            name: 'Шампіньйони з сулугуні в клярі',
            descr: 'гриби, фарш, сир сулугуні, часник, вершкове масло',
            img: 'url.url',
            price: 200,
          },
          {
            id: '060105',
            name: 'Телятина з лобіо (рисом)',
            descr: '1 пор',
            img: 'url.url',
            price: 100,
          },
          {
            id: '060106',
            name: 'Телятина з лобіо (рисом) подвійна',
            descr: '1 пор',
            img: 'url.url',
            price: 190,
          },
        ],
      },
      {
        id: 'fish dishes',
        title: 'Страви з риби',
        items: [
          {
            id: '060201',
            name: 'Риба в клярі',
            descr: 'хек, мука, яйце (100г)',
            img: 'url.url',
            price: 40,
          },
          {
            id: '060202',
            name: 'Жульєн рибний з грибами',
            descr: '1 пор',
            img: 'url.url',
            price: 37,
          },
          {
            id: '060203',
            name: 'Кальмар в сметані',
            descr: '1 пор',
            img: 'url.url',
            price: 130,
          },
          {
            id: '060204',
            name: 'Стейк з лосося',
            descr: '100г',
            img: 'url.url',
            price: 200,
          },
          {
            id: '060205',
            name: 'Скумбрія печена',
            descr: '1шт',
            img: 'url.url',
            price: 260,
          },
          {
            id: '060206',
            name: 'Креветка в соусі чікмерулі',
            descr: '1 пор',
            img: 'url.url',
            price: 280,
          },
          {
            id: '060207',
            name: 'Карп печений',
            descr: '100г',
            img: 'url.url',
            price: 40,
          },
          {
            id: '060208',
            name: 'Карп жарений',
            descr: '100г',
            img: 'url.url',
            price: 40,
          },
          {
            id: '060209',
            name: 'Форель',
            descr: '100г',
            img: 'url.url',
            price: 100,
          },
          {
            id: '060210',
            name: 'Риба: дорадо/сібас',
            descr: '100г',
            img: 'url.url',
            price: 80,
          },
        ],
      },
      {
        id: 'soups',
        title: 'Супчики',
        items: [
          {
            id: '060301',
            name: 'Суп "Харчо"',
            descr: '1 пор',
            img: 'url.url',
            price: 90,
          },
          {
            id: '060302',
            name: 'Уха з лосося',
            descr: '1 пор',
            img: 'url.url',
            price: 90,
          },
          {
            id: '060303',
            name: 'Суп з фрикадельками',
            descr: '1 пор',
            img: 'url.url',
            price: 80,
          },
          {
            id: '060304',
            name: 'Бульйон з пельменями',
            descr: '1 пор',
            img: 'url.url',
            price: 60,
          },
          {
            id: '060305',
            name: 'Бульйон з фрикадельками',
            descr: '1 пор',
            img: 'url.url',
            price: 80,
          },
          {
            id: '060306',
            name: "Солянка збірна м'ясна",
            descr: '1 пор',
            img: 'url.url',
            price: 95,
          },
          {
            id: '060307',
            name: 'Борщ з компліментом від шеф повара',
            descr: '1 пор',
            img: 'url.url',
            price: 100,
          },
        ],
      },
      {
        id: 'side-dishes',
        title: 'Гарніри',
        items: [
          {
            id: '060401',
            name: 'Картопляне пюре',
            descr: '1 пор',
            img: 'url.url',
            price: 100,
          },
          {
            id: '060402',
            name: 'Картопляне пюре (порційне)',
            descr: '1 пор',
            img: 'url.url',
            price: 40,
          },
          {
            id: '060403',
            name: 'Картопля по-домашньому',
            descr: '300г',
            img: 'url.url',
            price: 50,
          },
          {
            id: '060404',
            name: 'Картопля жарена',
            descr: '500г',
            img: 'url.url',
            price: 90,
          },
          {
            id: '060405',
            name: 'Картопля по-домашньому',
            descr: '1 кг',
            img: 'url.url',
            price: 100,
          },
          {
            id: '060406',
            name: 'Картопля по-царськи (з сулугуні)',
            descr: '1 пор',
            img: 'url.url',
            price: 180,
          },
          {
            id: '060407',
            name: 'Рис з грибами',
            descr: '1 пор',
            img: 'url.url',
            price: 40,
          },
          {
            id: '060408',
            name: 'Лобіо',
            descr: '1 пор',
            img: 'url.url',
            price: 50,
          },
          {
            id: '060409',
            name: 'Макарони по "Гурійськи"',
            descr: 'макарони, томат, спеції грузинські, бекон, фарш, пармезан',
            img: 'url.url',
            price: 220,
          },
          {
            id: '060410',
            name: 'Деруни',
            descr: '1 пор',
            img: 'url.url',
            price: 80,
          },
        ],
      },
    ],
  },
  {
    id: 'cold-dishes',
    title: 'Холодні закуски',
    subcategories: [
      {
        id: 'cold-dishes-sub',
        title: 'Холодні закуски',
        items: [
          {
            id: '070101',
            name: 'Цицака',
            descr: 'перець гриль в маринаді з сиром та горіхами',
            img: 'url.url',
            price: 220,
          },
          {
            id: '070102',
            name: 'Млинці з лососем',
            descr: '1 пор',
            img: 'url.url',
            price: 220,
          },
          {
            id: '070103',
            name: 'Тевзі з картоплею в мундирі',
            descr: '1 пор (скумбрія власного соління)',
            img: 'url.url',
            price: 120,
          },
          {
            id: '070104',
            name: 'Рулетики з оселедцем',
            descr: '1 пор',
            img: 'url.url',
            price: 75,
          },
          {
            id: '070105',
            name: 'Рулетики з баклажану',
            descr: '1 пор',
            img: 'url.url',
            price: 200,
          },
          {
            id: '070106',
            name: 'Рибна тарілка',
            descr: 'лосось, масляна, мідія, оливки (500г)',
            img: 'url.url',
            price: 750,
          },
          {
            id: '070107',
            name: 'Сет закусок',
            descr:
              'корзинка з лососем, з креветкою, жульєн,брускета з баликом та печеним перцем',
            img: 'url.url',
            price: 600,
          },
          {
            id: '070108',
            name: 'Сало з часником',
            descr: '100г',
            img: 'url.url',
            price: 50,
          },
          {
            id: '070109',
            name: 'Сирна тарілка',
            descr: '200г',
            img: 'url.url',
            price: 100,
          },
          {
            id: '070110',
            name: 'Овочева тарілка',
            descr: '300г',
            img: 'url.url',
            price: 120,
          },
          {
            id: '070111',
            name: 'Лимон, апельсин',
            descr: '100г',
            img: 'url.url',
            price: 20,
          },
          {
            id: '070112',
            name: 'Яблуко',
            descr: '100г',
            img: 'url.url',
            price: 15,
          },
          {
            id: '070113',
            name: "М'ясна тарілка",
            descr: '300г',
            img: 'url.url',
            price: 250,
          },
        ],
      },
      {
        id: 'pickles',
        title: 'Соління',
        items: [
          {
            id: '070201',
            name: 'Мариновані печериці',
            descr: '100г',
            img: 'url.url',
            price: 60,
          },
          {
            id: '070202',
            name: 'Солені огірочки',
            descr: '100г',
            img: 'url.url',
            price: 40,
          },
          {
            id: '070203',
            name: 'Капуста Пелюстка',
            descr: '100г',
            img: 'url.url',
            price: 25,
          },
          {
            id: '070204',
            name: 'Помідори квашені',
            descr: '100г',
            img: 'url.url',
            price: 35,
          },
          {
            id: '070205',
            name: 'Буряк маринований',
            descr: '100г',
            img: 'url.url',
            price: 25,
          },
        ],
      },
      {
        id: 'sauces',
        title: 'Соуси',
        items: [
          {
            id: '070301',
            name: 'Соус "Грузинський"',
            descr: '50г',
            img: 'url.url',
            price: 45,
          },
          {
            id: '070302',
            name: 'Соус "Сацебел"',
            descr: '200г',
            img: 'url.url',
            price: 70,
          },
          {
            id: '070303',
            name: 'Ягідний соус до птиці',
            descr: '50г',
            img: 'url.url',
            price: 40,
          },
          {
            id: '070304',
            name: 'Сметана',
            descr: '100г',
            img: 'url.url',
            price: 40,
          },
          {
            id: '070305',
            name: 'Майонез',
            descr: '100г',
            img: 'url.url',
            price: 40,
          },
          {
            id: '070306',
            name: 'Ткемалі',
            descr: '50г',
            img: 'url.url',
            price: 40,
          },
          {
            id: '070307',
            name: 'Горіховий',
            descr: '100г',
            img: 'url.url',
            price: 70,
          },
          {
            id: '070308',
            name: 'Тар-тар',
            descr: '50г',
            img: 'url.url',
            price: 40,
          },
        ],
      },
    ],
  },
  {
    id: 'strong-alcohol',
    title: 'Міцний алкоголь',
    subcategories: [
      {
        id: 'vodka',
        title: 'Горілка',
        items: [
          {
            id: '080101',
            name: 'Немирів LEX',
            descr: '0,5л',
            img: 'url.url',
            price: 700,
          },
          {
            id: '080102',
            name: 'Немирів Делікат',
            descr: '0,5л',
            img: 'url.url',
            price: 200,
          },
          {
            id: '080103',
            name: 'Немирів Делікат',
            descr: '0,7л',
            img: 'url.url',
            price: 240,
          },
          {
            id: '080104',
            name: 'Немирів Оригінал',
            descr: '0,5л',
            img: 'url.url',
            price: 200,
          },
          {
            id: '080105',
            name: 'Немирів Оригінал',
            descr: '0,7л',
            img: 'url.url',
            price: 240,
          },
          {
            id: '080106',
            name: 'GreenDay оригінал',
            descr: '0,5л',
            img: 'url.url',
            price: 200,
          },
          {
            id: '080107',
            name: 'GreenDay оригінал',
            descr: '0,7л',
            img: 'url.url',
            price: 240,
          },
          {
            id: '080108',
            name: 'GreenDay преміум',
            descr: '0,5л',
            img: 'url.url',
            price: 200,
          },
          {
            id: '080109',
            name: 'GreenDay преміум',
            descr: '0,7л',
            img: 'url.url',
            price: 250,
          },
          {
            id: '080110',
            name: 'Нікіта',
            descr: '0,5л',
            img: 'url.url',
            price: 300,
          },
          {
            id: '080111',
            name: 'BJM',
            descr: '0,5л',
            img: 'url.url',
            price: 280,
          },
          {
            id: '080112',
            name: 'Hetman',
            descr: '0,5л',
            img: 'url.url',
            price: 300,
          },
          {
            id: '080112',
            name: 'Hetman',
            descr: '0,7л',
            img: 'url.url',
            price: 350,
          },
        ],
      },
      {
        id: 'cognaс',
        title: 'Коньяк',
        items: [
          {
            id: '080201',
            name: 'Старий Кахеті 4*',
            descr: '0,5л',
            img: 'url.url',
            price: 500,
          },
          {
            id: '080202',
            name: 'Старий кахеті 5*',
            descr: '0,5л',
            img: 'url.url',
            price: 500,
          },
          {
            id: '080203',
            name: 'Азнаурі 3*',
            descr: '0,5л',
            img: 'url.url',
            price: 300,
          },
          {
            id: '080204',
            name: 'Азнаурі 4*',
            descr: '0,5л',
            img: 'url.url',
            price: 320,
          },
          {
            id: '080205',
            name: 'Азнаурі 5**',
            descr: '0,5л',
            img: 'url.url',
            price: 350,
          },
          {
            id: '080206',
            name: 'Аджарі 3*',
            descr: '0,5л',
            img: 'url.url',
            price: 320,
          },
          {
            id: '080207',
            name: 'Аджарі 4*',
            descr: '0,5л',
            img: 'url.url',
            price: 340,
          },
          {
            id: '080208',
            name: 'Metaxa 5*',
            descr: '0,5л',
            img: 'url.url',
            price: 750,
          },
          {
            id: '080209',
            name: 'Metaxa 5*',
            descr: '0,7л',
            img: 'url.url',
            price: 900,
          },
        ],
      },
      {
        id: 'whiskey',
        title: 'Віскі',
        items: [
          {
            id: '080301',
            name: 'Ром Капітан Морган',
            descr: '0,5л',
            img: 'url.url',
            price: 900,
          },
          {
            id: '080302',
            name: 'Віскі Джим бім бурбон',
            descr: '0,5л',
            img: 'url.url',
            price: 980,
          },
          {
            id: '080303',
            name: 'Scottish collie',
            descr: '0,5л',
            img: 'url.url',
            price: 800,
          },
          {
            id: '080304',
            name: "Ballantine's",
            descr: '0,5л',
            img: 'url.url',
            price: 1100,
          },
          {
            id: '080305',
            name: 'Jameson',
            descr: '0,5л',
            img: 'url.url',
            price: 1100,
          },
          {
            id: '080306',
            name: 'Metaxa',
            descr: '0,5л',
            img: 'url.url',
            price: 900,
          },
        ],
      },
      {
        id: 'wines',
        title: 'Вина',
        items: [
          {
            id: '080401',
            name: 'Вино',
            descr: '0,7л',
            img: 'url.url',
            price: 60,
          },
        ],
      },
      {
        id: 'sparkling wines',
        title: 'Ігристі вина',
        items: [
          {
            id: '080501',
            name: 'Асті біле солодке',
            descr: '0,75л',
            img: 'url.url',
            price: 300,
          },
          {
            id: '080502',
            name: 'Асті біле солодке Таїрово',
            descr: '0,75л',
            img: 'url.url',
            price: 300,
          },
          {
            id: '080503',
            name: "Фраголіно б'янко",
            descr: '0,75л',
            img: 'url.url',
            price: 400,
          },
          {
            id: '080504',
            name: 'Фраголіно россо',
            descr: '0,75л',
            img: 'url.url',
            price: 400,
          },
          {
            id: '080505',
            name: 'Фраголіно брют',
            descr: '0,75л',
            img: 'url.url',
            price: 400,
          },
        ],
      },
    ],
  },
];
